[workspace]
resolver = "2"
member = [ ]
members = ["math", "testapp"]

[workspace.dependencies]
geo = "0.28"
glam = "0.27"
bevy_math = "0.14"
geo-buffer = { git = "https://github.com/RobWalt/geo-buffer.git", branch = "update" }

strum = "0.26"

bevy = "0.14"
bevy-inspector-egui = "0.25"
bevy_egui = "0.28"
bevy_mod_picking = "0.20"

math = { path = "math" }
