[workspace]
resolver = "2"
members = ["selo", "testapp"]

[workspace.dependencies]
geo = { git = "https://github.com/RobWalt/geo.git", branch = "feat/spade-boolops" }
glam = "0.27"
bevy_math = "0.14"
geo-buffer = { git = "https://github.com/RobWalt/geo-buffer.git", branch = "update" }
bevy_reflect = "0.14"

strum = "0.26"
itertools = "0.13"

bevy = "0.14"
bevy-inspector-egui = "0.25"
bevy_egui = "0.28"
bevy_mod_picking = "0.20"

selo = { path = "selo" }
