[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
geo.workspace = true
glam.workspace = true
bevy_math.workspace = true
geo-buffer.workspace = true
itertools.workspace = true

bevy_reflect.workspace = true
