[package]
name = "selo"
version = "0.1.0"
edition = "2021"

[features]
default = []
wkt = ["dep:serde"]

[dependencies]
geo.workspace = true
glam.workspace = true
bevy_math.workspace = true
geo-buffer.workspace = true
itertools.workspace = true
num-traits = "0.2"
thiserror = "1.0"
serde = { workspace = true, optional = true }

bevy_reflect = { workspace = true, optional = true}
